export const filterKeys = (data) => {
  return Object.keys(data).filter(
    (key) =>
      ![
        "hofAboutMe",
        "hofUserName",
        "spId",
        "chId",
        "nomineeId",
        "locationId",
        "familyDoctorId",
        "hospitalId",
        "insuranceAgentId",
        "specialDoctorId",
        "stockBrokerId",
        "taxConsultantId",
        "mediClaimPoliciesId",
        "fireBurglaryInsuranceId",
        "personalInsuranceId",
        "bankId",
        "amcAndWarrantiesId",
        "walletId",
        "rationCardId",
        "incomeTaxId",
        "mutualFundDetailsSIPsId",
        "ecsMandateDetailsId",
        "lockerId",
        "loanAccountId",
        "creditCardId",
        "pensionId",
        "electricityWaterMeterId",
        "landlineId",
        "atmCardId",
        "gasCylinderId",
        "gasPipelineId",
        "publicProvidentFundId",
        "passportDetailsId",
        "drivingLicenceId",
        "adharCardDetailsId",
        "creditorOrDebitorID",
        "panDetailsId",
      ].includes(key) && !Array.isArray(data[key]) //exclude keys whose values are arrays
  );
};
